{{- range $key, $value := .Values.apps }}
{{- $_ := merge $value (set (dict) "name" $key ) }}
{{- $templateVals := dict "root" $ "curApp" $value }}
{{- include "argocd.app" $templateVals }}
{{- end}}

