---
#In general, most values can have helm tempates embedded in them, and .curApp will be populated
# with the pre-merged/inherited values for an application

#When putting a values file in for your app group, remember this is a subchart so indent everything under:
#argocd-app-groups:


project: test-project
repoUrl: repoUrlValue
repoBranch: main

apps:
  test-minimal:
    namespace: test-namespace
    addNamespacePrefix: false
    addNamePrefix: false
    valueFiles:
      - values-{{.curApp.name}}.yaml
  test2:
    name: overridden-name-here
    namespace: test2-namespace
    project: otherProject
    addNamespacePrefix: true
    path: myAppPath
    syncPolicy: |
      automated:
        prune: true
        allowEmpty: true
    ignoreDifferences: |
      - group: apps
        kind: Deployment
        name: {{ .curApp.name }}
        namespace: "{{ .curApp.namespacePrefix }}-test2-namespace"
        jsonPointers:
          - /spec/replicas
    annotations: |
      team: "{{ .Values.global.clusterInfo.team }}"
    extraValues: |
      test-extra-value:
        myvalue-{{ .Values.global.clusterInfo.environment }}: {{ .Values.global.clusterInfo.controlPlaneUrl }}
      simple: "key-value"
global:
  clusterInfo:
    accountId: "testAccountId"
    accountName: "testAccountName"
    controlPlaneUrl: "testControlPlaneUrl"
    clusterName: "test-cluster-name"
    region: "testRegion"
    environment: "dev"
    team: "testTeam"
