---

# These values are used as the default
# for all the apps from this appGroup
project: "" #defaults to "default"
repoUrl: "repoUrl required" #required
repoBranch: "" #defaults to "main"

applicationNamespace: "" #defaults to "argocd"

#by default these are added to all apps
#typically used for dev/stage/prod prefixes
#namespacePrefix: "" #defaults to global.clusterInfo.environment
#namePrefix: "" #defaults to global.clusterInfo.environment


apps:
  my-app:
    namespace: "my-namespace"
#    releaseName: "helm-release"
#    project: ""
#    annotations: {}
#    labels: {}
#    ignoreDifferences: false
#    addNamePrefix: true
#    namePrefix: "" #defaults to environment
#    addNamespacePrefix: true
#    namespacePrefix: "" #defaults to environment
#    syncPolicy: {}
#    repoUrl: ""
#    repoBranch: ""
#    repoPath: {{ .curApp.name }}
#    valueFiles:
#      - values.yaml
#      - values-{{ .curApp.environment }}


# these values are passed to each of the apps that the app group manages
# It is highly recommended to use "environment" if you have different clusters you are deploying to
#global:
#  clusterInfo:
#    accountId: ""
#    accountName: ""
#    controlPlaneUrl: ""
#    clusterName: "" #defaults to local cluster (https://kubernetes.default.svc)
#    region: ""
#    environment: ""
#    team: ""
